name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        jdk: ['11', '17']
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'

    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
      
    - name: Run Tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test
